-- Spain: provinces (postal code prefix) and autonomous cities
INSERT INTO COUNTRY_REGIONS (country_id, region_id, description, region_key) VALUES
    ('ES', '01', 'Alava', 'region.ES.01'),
    ('ES', '02', 'Albacete', 'region.ES.02'),
    ('ES', '03', 'Alicante', 'region.ES.03'),
    ('ES', '04', 'Almeria', 'region.ES.04'),
    ('ES', '05', 'Avila', 'region.ES.05'),
    ('ES', '06', 'Badajoz', 'region.ES.06'),
    ('ES', '07', 'Balearic Islands', 'region.ES.07'),
    ('ES', '08', 'Barcelona', 'region.ES.08'),
    ('ES', '09', 'Burgos', 'region.ES.09'),
    ('ES', '10', 'Caceres', 'region.ES.10'),
    ('ES', '11', 'Cadiz', 'region.ES.11'),
    ('ES', '12', 'Castellon', 'region.ES.12'),
    ('ES', '13', 'Ciudad Real', 'region.ES.13'),
    ('ES', '14', 'Cordoba', 'region.ES.14'),
    ('ES', '15', 'A Coruna', 'region.ES.15'),
    ('ES', '16', 'Cuenca', 'region.ES.16'),
    ('ES', '17', 'Girona', 'region.ES.17'),
    ('ES', '18', 'Granada', 'region.ES.18'),
    ('ES', '19', 'Guadalajara', 'region.ES.19'),
    ('ES', '20', 'Gipuzkoa', 'region.ES.20'),
    ('ES', '21', 'Huelva', 'region.ES.21'),
    ('ES', '22', 'Huesca', 'region.ES.22'),
    ('ES', '23', 'Jaen', 'region.ES.23'),
    ('ES', '24', 'Leon', 'region.ES.24'),
    ('ES', '25', 'Lleida', 'region.ES.25'),
    ('ES', '26', 'La Rioja', 'region.ES.26'),
    ('ES', '27', 'Lugo', 'region.ES.27'),
    ('ES', '28', 'Madrid', 'region.ES.28'),
    ('ES', '29', 'Malaga', 'region.ES.29'),
    ('ES', '30', 'Murcia', 'region.ES.30'),
    ('ES', '31', 'Navarre', 'region.ES.31'),
    ('ES', '32', 'Ourense', 'region.ES.32'),
    ('ES', '33', 'Asturias', 'region.ES.33'),
    ('ES', '34', 'Palencia', 'region.ES.34'),
    ('ES', '35', 'Las Palmas', 'region.ES.35'),
    ('ES', '36', 'Pontevedra', 'region.ES.36'),
    ('ES', '37', 'Salamanca', 'region.ES.37'),
    ('ES', '38', 'Santa Cruz de Tenerife', 'region.ES.38'),
    ('ES', '39', 'Cantabria', 'region.ES.39'),
    ('ES', '40', 'Segovia', 'region.ES.40'),
    ('ES', '41', 'Seville', 'region.ES.41'),
    ('ES', '42', 'Soria', 'region.ES.42'),
    ('ES', '43', 'Tarragona', 'region.ES.43'),
    ('ES', '44', 'Teruel', 'region.ES.44'),
    ('ES', '45', 'Toledo', 'region.ES.45'),
    ('ES', '46', 'Valencia', 'region.ES.46'),
    ('ES', '47', 'Valladolid', 'region.ES.47'),
    ('ES', '48', 'Biscay', 'region.ES.48'),
    ('ES', '49', 'Zamora', 'region.ES.49'),
    ('ES', '50', 'Zaragoza', 'region.ES.50'),
    ('ES', '51', 'Ceuta', 'region.ES.51'),
    ('ES', '52', 'Melilla', 'region.ES.52');

-- France: regions (ISO 3166-2:FR)
INSERT INTO COUNTRY_REGIONS (country_id, region_id, description, region_key) VALUES
    ('FR', 'ARA', 'Auvergne-Rhone-Alpes', 'region.FR.ARA'),
    ('FR', 'BFC', 'Bourgogne-Franche-Comte', 'region.FR.BFC'),
    ('FR', 'BRE', 'Brittany', 'region.FR.BRE'),
    ('FR', 'CVL', 'Centre-Val de Loire', 'region.FR.CVL'),
    ('FR', 'COR', 'Corsica', 'region.FR.COR'),
    ('FR', 'GES', 'Grand Est', 'region.FR.GES'),
    ('FR', 'HDF', 'Hauts-de-France', 'region.FR.HDF'),
    ('FR', 'IDF', 'Ile-de-France', 'region.FR.IDF'),
    ('FR', 'NOR', 'Normandy', 'region.FR.NOR'),
    ('FR', 'NAQ', 'Nouvelle-Aquitaine', 'region.FR.NAQ'),
    ('FR', 'OCC', 'Occitanie', 'region.FR.OCC'),
    ('FR', 'PDL', 'Pays de la Loire', 'region.FR.PDL'),
    ('FR', 'PAC', 'Provence-Alpes-Cote d''Azur', 'region.FR.PAC'),
    ('FR', 'GUA', 'Guadeloupe', 'region.FR.GUA'),
    ('FR', 'MTQ', 'Martinique', 'region.FR.MTQ'),
    ('FR', 'GUF', 'French Guiana', 'region.FR.GUF'),
    ('FR', 'LRE', 'La Reunion', 'region.FR.LRE'),
    ('FR', 'MAY', 'Mayotte', 'region.FR.MAY');

-- Germany: federal states (ISO 3166-2:DE)
INSERT INTO COUNTRY_REGIONS (country_id, region_id, description, region_key) VALUES
    ('DE', 'BW', 'Baden-Wurttemberg', 'region.DE.BW'),
    ('DE', 'BY', 'Bavaria', 'region.DE.BY'),
    ('DE', 'BE', 'Berlin', 'region.DE.BE'),
    ('DE', 'BB', 'Brandenburg', 'region.DE.BB'),
    ('DE', 'HB', 'Bremen', 'region.DE.HB'),
    ('DE', 'HH', 'Hamburg', 'region.DE.HH'),
    ('DE', 'HE', 'Hesse', 'region.DE.HE'),
    ('DE', 'MV', 'Mecklenburg-Vorpommern', 'region.DE.MV'),
    ('DE', 'NI', 'Lower Saxony', 'region.DE.NI'),
    ('DE', 'NW', 'North Rhine-Westphalia', 'region.DE.NW'),
    ('DE', 'RP', 'Rhineland-Palatinate', 'region.DE.RP'),
    ('DE', 'SL', 'Saarland', 'region.DE.SL'),
    ('DE', 'SN', 'Saxony', 'region.DE.SN'),
    ('DE', 'ST', 'Saxony-Anhalt', 'region.DE.ST'),
    ('DE', 'SH', 'Schleswig-Holstein', 'region.DE.SH'),
    ('DE', 'TH', 'Thuringia', 'region.DE.TH');

-- United Kingdom: regions of England plus constituent countries
INSERT INTO COUNTRY_REGIONS (country_id, region_id, description, region_key) VALUES
    ('GB', 'NE', 'North East England', 'region.GB.NE'),
    ('GB', 'NW', 'North West England', 'region.GB.NW'),
    ('GB', 'YH', 'Yorkshire and the Humber', 'region.GB.YH'),
    ('GB', 'EM', 'East Midlands', 'region.GB.EM'),
    ('GB', 'WM', 'West Midlands', 'region.GB.WM'),
    ('GB', 'EE', 'East of England', 'region.GB.EE'),
    ('GB', 'LON', 'London', 'region.GB.LON'),
    ('GB', 'SE', 'South East England', 'region.GB.SE'),
    ('GB', 'SW', 'South West England', 'region.GB.SW'),
    ('GB', 'SCT', 'Scotland', 'region.GB.SCT'),
    ('GB', 'WLS', 'Wales', 'region.GB.WLS'),
    ('GB', 'NIR', 'Northern Ireland', 'region.GB.NIR');

-- United States: states
INSERT INTO COUNTRY_REGIONS (country_id, region_id, description, region_key) VALUES
    ('US', 'AL', 'Alabama', 'region.US.AL'),
    ('US', 'AK', 'Alaska', 'region.US.AK'),
    ('US', 'AZ', 'Arizona', 'region.US.AZ'),
    ('US', 'AR', 'Arkansas', 'region.US.AR'),
    ('US', 'CA', 'California', 'region.US.CA'),
    ('US', 'CO', 'Colorado', 'region.US.CO'),
    ('US', 'CT', 'Connecticut', 'region.US.CT'),
    ('US', 'DE', 'Delaware', 'region.US.DE'),
    ('US', 'FL', 'Florida', 'region.US.FL'),
    ('US', 'GA', 'Georgia', 'region.US.GA'),
    ('US', 'HI', 'Hawaii', 'region.US.HI'),
    ('US', 'ID', 'Idaho', 'region.US.ID'),
    ('US', 'IL', 'Illinois', 'region.US.IL'),
    ('US', 'IN', 'Indiana', 'region.US.IN'),
    ('US', 'IA', 'Iowa', 'region.US.IA'),
    ('US', 'KS', 'Kansas', 'region.US.KS'),
    ('US', 'KY', 'Kentucky', 'region.US.KY'),
    ('US', 'LA', 'Louisiana', 'region.US.LA'),
    ('US', 'ME', 'Maine', 'region.US.ME'),
    ('US', 'MD', 'Maryland', 'region.US.MD'),
    ('US', 'MA', 'Massachusetts', 'region.US.MA'),
    ('US', 'MI', 'Michigan', 'region.US.MI'),
    ('US', 'MN', 'Minnesota', 'region.US.MN'),
    ('US', 'MS', 'Mississippi', 'region.US.MS'),
    ('US', 'MO', 'Missouri', 'region.US.MO'),
    ('US', 'MT', 'Montana', 'region.US.MT'),
    ('US', 'NE', 'Nebraska', 'region.US.NE'),
    ('US', 'NV', 'Nevada', 'region.US.NV'),
    ('US', 'NH', 'New Hampshire', 'region.US.NH'),
    ('US', 'NJ', 'New Jersey', 'region.US.NJ'),
    ('US', 'NM', 'New Mexico', 'region.US.NM'),
    ('US', 'NY', 'New York', 'region.US.NY'),
    ('US', 'NC', 'North Carolina', 'region.US.NC'),
    ('US', 'ND', 'North Dakota', 'region.US.ND'),
    ('US', 'OH', 'Ohio', 'region.US.OH'),
    ('US', 'OK', 'Oklahoma', 'region.US.OK'),
    ('US', 'OR', 'Oregon', 'region.US.OR'),
    ('US', 'PA', 'Pennsylvania', 'region.US.PA'),
    ('US', 'RI', 'Rhode Island', 'region.US.RI'),
    ('US', 'SC', 'South Carolina', 'region.US.SC'),
    ('US', 'SD', 'South Dakota', 'region.US.SD'),
    ('US', 'TN', 'Tennessee', 'region.US.TN'),
    ('US', 'TX', 'Texas', 'region.US.TX'),
    ('US', 'UT', 'Utah', 'region.US.UT'),
    ('US', 'VT', 'Vermont', 'region.US.VT'),
    ('US', 'VA', 'Virginia', 'region.US.VA'),
    ('US', 'WA', 'Washington', 'region.US.WA'),
    ('US', 'WV', 'West Virginia', 'region.US.WV'),
    ('US', 'WI', 'Wisconsin', 'region.US.WI'),
    ('US', 'WY', 'Wyoming', 'region.US.WY');
