INSERT INTO COUNTRIES (country_id, description, country_key) VALUES
    ('AD', 'Andorra', 'country.AD'),
    ('AE', 'United Arab Emirates', 'country.AE'),
    ('AF', 'Afghanistan', 'country.AF'),
    ('AG', 'Antigua and Barbuda', 'country.AG'),
    ('AI', 'Anguilla', 'country.AI'),
    ('AL', 'Albania', 'country.AL'),
    ('AM', 'Armenia', 'country.AM'),
    ('AO', 'Angola', 'country.AO'),
    ('AQ', 'Antarctica', 'country.AQ'),
    ('AR', 'Argentina', 'country.AR'),
    ('AS', 'American Samoa', 'country.AS'),
    ('AT', 'Austria', 'country.AT'),
    ('AU', 'Australia', 'country.AU'),
    ('AW', 'Aruba', 'country.AW'),
    ('AX', 'Aland Islands', 'country.AX'),
    ('AZ', 'Azerbaijan', 'country.AZ'),
    ('BA', 'Bosnia and Herzegovina', 'country.BA'),
    ('BB', 'Barbados', 'country.BB'),
    ('BD', 'Bangladesh', 'country.BD'),
    ('BE', 'Belgium', 'country.BE'),
    ('BF', 'Burkina Faso', 'country.BF'),
    ('BG', 'Bulgaria', 'country.BG'),
    ('BH', 'Bahrain', 'country.BH'),
    ('BI', 'Burundi', 'country.BI'),
    ('BJ', 'Benin', 'country.BJ'),
    ('BL', 'Saint Barthelemy', 'country.BL'),
    ('BM', 'Bermuda', 'country.BM'),
    ('BN', 'Brunei Darussalam', 'country.BN'),
    ('BO', 'Bolivia', 'country.BO'),
    ('BQ', 'Bonaire, Sint Eustatius and Saba', 'country.BQ'),
    ('BR', 'Brazil', 'country.BR'),
    ('BS', 'Bahamas', 'country.BS'),
    ('BT', 'Bhutan', 'country.BT'),
    ('BV', 'Bouvet Island', 'country.BV'),
    ('BW', 'Botswana', 'country.BW'),
    ('BY', 'Belarus', 'country.BY'),
    ('BZ', 'Belize', 'country.BZ'),
    ('CA', 'Canada', 'country.CA'),
    ('CC', 'Cocos Islands', 'country.CC'),
    ('CD', 'Congo, Democratic Republic', 'country.CD'),
    ('CF', 'Central African Republic', 'country.CF'),
    ('CG', 'Congo', 'country.CG'),
    ('CH', 'Switzerland', 'country.CH'),
    ('CI', 'Cote d''Ivoire', 'country.CI'),
    ('CK', 'Cook Islands', 'country.CK'),
    ('CL', 'Chile', 'country.CL'),
    ('CM', 'Cameroon', 'country.CM'),
    ('CN', 'China', 'country.CN'),
    ('CO', 'Colombia', 'country.CO'),
    ('CR', 'Costa Rica', 'country.CR'),
    ('CU', 'Cuba', 'country.CU'),
    ('CV', 'Cabo Verde', 'country.CV'),
    ('CW', 'Curacao', 'country.CW'),
    ('CX', 'Christmas Island', 'country.CX'),
    ('CY', 'Cyprus', 'country.CY'),
    ('CZ', 'Czechia', 'country.CZ'),
    ('DE', 'Germany', 'country.DE'),
    ('DJ', 'Djibouti', 'country.DJ'),
    ('DK', 'Denmark', 'country.DK'),
    ('DM', 'Dominica', 'country.DM'),
    ('DO', 'Dominican Republic', 'country.DO'),
    ('DZ', 'Algeria', 'country.DZ'),
    ('EC', 'Ecuador', 'country.EC'),
    ('EE', 'Estonia', 'country.EE'),
    ('EG', 'Egypt', 'country.EG'),
    ('EH', 'Western Sahara', 'country.EH'),
    ('ER', 'Eritrea', 'country.ER'),
    ('ES', 'Spain', 'country.ES'),
    ('ET', 'Ethiopia', 'country.ET'),
    ('FI', 'Finland', 'country.FI'),
    ('FJ', 'Fiji', 'country.FJ'),
    ('FK', 'Falkland Islands', 'country.FK'),
    ('FM', 'Micronesia', 'country.FM'),
    ('FO', 'Faroe Islands', 'country.FO'),
    ('FR', 'France', 'country.FR'),
    ('GA', 'Gabon', 'country.GA'),
    ('GB', 'United Kingdom', 'country.GB'),
    ('GD', 'Grenada', 'country.GD'),
    ('GE', 'Georgia', 'country.GE'),
    ('GF', 'French Guiana', 'country.GF'),
    ('GG', 'Guernsey', 'country.GG'),
    ('GH', 'Ghana', 'country.GH'),
    ('GI', 'Gibraltar', 'country.GI'),
    ('GL', 'Greenland', 'country.GL'),
    ('GM', 'Gambia', 'country.GM'),
    ('GN', 'Guinea', 'country.GN'),
    ('GP', 'Guadeloupe', 'country.GP'),
    ('GQ', 'Equatorial Guinea', 'country.GQ'),
    ('GR', 'Greece', 'country.GR'),
    ('GS', 'South Georgia and the South Sandwich Islands', 'country.GS'),
    ('GT', 'Guatemala', 'country.GT'),
    ('GU', 'Guam', 'country.GU'),
    ('GW', 'Guinea-Bissau', 'country.GW'),
    ('GY', 'Guyana', 'country.GY'),
    ('HK', 'Hong Kong', 'country.HK'),
    ('HM', 'Heard Island and McDonald Islands', 'country.HM'),
    ('HN', 'Honduras', 'country.HN'),
    ('HR', 'Croatia', 'country.HR'),
    ('HT', 'Haiti', 'country.HT'),
    ('HU', 'Hungary', 'country.HU'),
    ('ID', 'Indonesia', 'country.ID'),
    ('IE', 'Ireland', 'country.IE'),
    ('IL', 'Israel', 'country.IL'),
    ('IM', 'Isle of Man', 'country.IM'),
    ('IN', 'India', 'country.IN'),
    ('IO', 'British Indian Ocean Territory', 'country.IO'),
    ('IQ', 'Iraq', 'country.IQ'),
    ('IR', 'Iran', 'country.IR'),
    ('IS', 'Iceland', 'country.IS'),
    ('IT', 'Italy', 'country.IT'),
    ('JE', 'Jersey', 'country.JE'),
    ('JM', 'Jamaica', 'country.JM'),
    ('JO', 'Jordan', 'country.JO'),
    ('JP', 'Japan', 'country.JP'),
    ('KE', 'Kenya', 'country.KE'),
    ('KG', 'Kyrgyzstan', 'country.KG'),
    ('KH', 'Cambodia', 'country.KH'),
    ('KI', 'Kiribati', 'country.KI'),
    ('KM', 'Comoros', 'country.KM'),
    ('KN', 'Saint Kitts and Nevis', 'country.KN'),
    ('KP', 'North Korea', 'country.KP'),
    ('KR', 'South Korea', 'country.KR'),
    ('KW', 'Kuwait', 'country.KW'),
    ('KY', 'Cayman Islands', 'country.KY'),
    ('KZ', 'Kazakhstan', 'country.KZ'),
    ('LA', 'Laos', 'country.LA'),
    ('LB', 'Lebanon', 'country.LB'),
    ('LC', 'Saint Lucia', 'country.LC'),
    ('LI', 'Liechtenstein', 'country.LI'),
    ('LK', 'Sri Lanka', 'country.LK'),
    ('LR', 'Liberia', 'country.LR'),
    ('LS', 'Lesotho', 'country.LS'),
    ('LT', 'Lithuania', 'country.LT'),
    ('LU', 'Luxembourg', 'country.LU'),
    ('LV', 'Latvia', 'country.LV'),
    ('LY', 'Libya', 'country.LY'),
    ('MA', 'Morocco', 'country.MA'),
    ('MC', 'Monaco', 'country.MC'),
    ('MD', 'Moldova', 'country.MD'),
    ('ME', 'Montenegro', 'country.ME'),
    ('MF', 'Saint Martin (French part)', 'country.MF'),
    ('MG', 'Madagascar', 'country.MG'),
    ('MH', 'Marshall Islands', 'country.MH'),
    ('MK', 'North Macedonia', 'country.MK'),
    ('ML', 'Mali', 'country.ML'),
    ('MM', 'Myanmar', 'country.MM'),
    ('MN', 'Mongolia', 'country.MN'),
    ('MO', 'Macao', 'country.MO'),
    ('MP', 'Northern Mariana Islands', 'country.MP'),
    ('MQ', 'Martinique', 'country.MQ'),
    ('MR', 'Mauritania', 'country.MR'),
    ('MS', 'Montserrat', 'country.MS'),
    ('MT', 'Malta', 'country.MT'),
    ('MU', 'Mauritius', 'country.MU'),
    ('MV', 'Maldives', 'country.MV'),
    ('MW', 'Malawi', 'country.MW'),
    ('MX', 'Mexico', 'country.MX'),
    ('MY', 'Malaysia', 'country.MY'),
    ('MZ', 'Mozambique', 'country.MZ'),
    ('NA', 'Namibia', 'country.NA'),
    ('NC', 'New Caledonia', 'country.NC'),
    ('NE', 'Niger', 'country.NE'),
    ('NF', 'Norfolk Island', 'country.NF'),
    ('NG', 'Nigeria', 'country.NG'),
    ('NI', 'Nicaragua', 'country.NI'),
    ('NL', 'Netherlands', 'country.NL'),
    ('NO', 'Norway', 'country.NO'),
    ('NP', 'Nepal', 'country.NP'),
    ('NR', 'Nauru', 'country.NR'),
    ('NU', 'Niue', 'country.NU'),
    ('NZ', 'New Zealand', 'country.NZ'),
    ('OM', 'Oman', 'country.OM'),
    ('PA', 'Panama', 'country.PA'),
    ('PE', 'Peru', 'country.PE'),
    ('PF', 'French Polynesia', 'country.PF'),
    ('PG', 'Papua New Guinea', 'country.PG'),
    ('PH', 'Philippines', 'country.PH'),
    ('PK', 'Pakistan', 'country.PK'),
    ('PL', 'Poland', 'country.PL'),
    ('PM', 'Saint Pierre and Miquelon', 'country.PM'),
    ('PN', 'Pitcairn', 'country.PN'),
    ('PR', 'Puerto Rico', 'country.PR'),
    ('PS', 'Palestine', 'country.PS'),
    ('PT', 'Portugal', 'country.PT'),
    ('PW', 'Palau', 'country.PW'),
    ('PY', 'Paraguay', 'country.PY'),
    ('QA', 'Qatar', 'country.QA'),
    ('RE', 'Reunion', 'country.RE'),
    ('RO', 'Romania', 'country.RO'),
    ('RS', 'Serbia', 'country.RS'),
    ('RU', 'Russian Federation', 'country.RU'),
    ('RW', 'Rwanda', 'country.RW'),
    ('SA', 'Saudi Arabia', 'country.SA'),
    ('SB', 'Solomon Islands', 'country.SB'),
    ('SC', 'Seychelles', 'country.SC'),
    ('SD', 'Sudan', 'country.SD'),
    ('SE', 'Sweden', 'country.SE'),
    ('SG', 'Singapore', 'country.SG'),
    ('SH', 'Saint Helena', 'country.SH'),
    ('SI', 'Slovenia', 'country.SI'),
    ('SJ', 'Svalbard and Jan Mayen', 'country.SJ'),
    ('SK', 'Slovakia', 'country.SK'),
    ('SL', 'Sierra Leone', 'country.SL'),
    ('SM', 'San Marino', 'country.SM'),
    ('SN', 'Senegal', 'country.SN'),
    ('SO', 'Somalia', 'country.SO'),
    ('SR', 'Suriname', 'country.SR'),
    ('SS', 'South Sudan', 'country.SS'),
    ('ST', 'Sao Tome and Principe', 'country.ST'),
    ('SV', 'El Salvador', 'country.SV'),
    ('SX', 'Sint Maarten (Dutch part)', 'country.SX'),
    ('SY', 'Syrian Arab Republic', 'country.SY'),
    ('SZ', 'Eswatini', 'country.SZ'),
    ('TC', 'Turks and Caicos Islands', 'country.TC'),
    ('TD', 'Chad', 'country.TD'),
    ('TF', 'French Southern Territories', 'country.TF'),
    ('TG', 'Togo', 'country.TG'),
    ('TH', 'Thailand', 'country.TH'),
    ('TJ', 'Tajikistan', 'country.TJ'),
    ('TK', 'Tokelau', 'country.TK'),
    ('TL', 'Timor-Leste', 'country.TL'),
    ('TM', 'Turkmenistan', 'country.TM'),
    ('TN', 'Tunisia', 'country.TN'),
    ('TO', 'Tonga', 'country.TO'),
    ('TR', 'Turkiye', 'country.TR'),
    ('TT', 'Trinidad and Tobago', 'country.TT'),
    ('TV', 'Tuvalu', 'country.TV'),
    ('TW', 'Taiwan', 'country.TW'),
    ('TZ', 'Tanzania', 'country.TZ'),
    ('UA', 'Ukraine', 'country.UA'),
    ('UG', 'Uganda', 'country.UG'),
    ('UM', 'United States Minor Outlying Islands', 'country.UM'),
    ('US', 'United States of America', 'country.US'),
    ('UY', 'Uruguay', 'country.UY'),
    ('UZ', 'Uzbekistan', 'country.UZ'),
    ('VA', 'Holy See', 'country.VA'),
    ('VC', 'Saint Vincent and the Grenadines', 'country.VC'),
    ('VE', 'Venezuela', 'country.VE'),
    ('VG', 'Virgin Islands (British)', 'country.VG'),
    ('VI', 'Virgin Islands (U.S.)', 'country.VI'),
    ('VN', 'Viet Nam', 'country.VN'),
    ('VU', 'Vanuatu', 'country.VU'),
    ('WF', 'Wallis and Futuna', 'country.WF'),
    ('WS', 'Samoa', 'country.WS'),
    ('YE', 'Yemen', 'country.YE'),
    ('YT', 'Mayotte', 'country.YT'),
    ('ZA', 'South Africa', 'country.ZA'),
    ('ZM', 'Zambia', 'country.ZM'),
    ('ZW', 'Zimbabwe', 'country.ZW');
