services:
  keycloak-db:
    image: postgres:16.13-alpine3.23
    container_name: churierpv2-keycloak-db
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    networks:
      - churi-network
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    command: start-dev
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: Pa55w0rd
    ports:
      - "9080:8080" # Ordinary port
      - "9100:9000" # Healthcheck port
    networks:
      - churi-network
    depends_on:
      - keycloak-db

networks:
  churi-network:
    name: churi-network
    driver: bridge

volumes:
  keycloak-db-data:
