services:
  keycloak-db:
    image: postgres:16.13-alpine3.23
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    networks:
      - churi-network
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: churierpv2-keycloak-db
      KEYCLOAK_DATABASE_NAME: keycloak_db
      KEYCLOAK_DATABASE_USER: keycloak_user
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    ports:
      - "9080:8080"
    networks:
      - churi-network
    depends_on:
      - keycloak-db

networks:
  churi-network:
    name: churi-network
    driver: bridge

volumes:
  keycloak-db-data:
